### ISSUE TITLE
rework the concurrency model

### ISSUE THREAD

**Issue by lucasart** [lucasart/zinc#11]
Avoid starting/closing engines with every game. Overhead is really too much, when playing very fast games. We need to create the UCI objects first, as a global, then threads find an idle one, to play a game.

**Comment by lucasart** [comment]
some progress here, with class UCIPair. All we need now is a thread pool, that chooses an available UCIPair to play a game.

**Comment by lucasart** [comment]
Actually, time controls should be managed by UCIPair, not UCI. This is because of an annoying thing in the UCI protocol, where you need to send the time for both colors, and know which engine plays which color.

**Comment by AndyGrant** [comment]
Submitted Pull Request to resolve

**Comment by lucasart** [comment]
merged in d8287c4e.
